# Generated by Django 4.0 on 2024-07-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subproducts',
            field=models.ManyToManyField(blank=True, to='shop.Product'),
        ),
    ]
